export const productlist = [
    { source: '/assets/icon_cctv.webp', alt:'cctv', width: 50, height: 50, status: false, nav: '', productName: 'CCTV Analytic', productDesc: 'Transform your security footage into actionable insights. Monitor and analyze video in real-time for enhanced safety and operational efficiency.' },
    { source: '/assets/icon_tv.webp', alt:'ip tv', width: 50, height: 50, status: true, nav: '/enterprise/internet', productName: 'IP TV', productDesc: 'Enjoy high-definition content streaming seamlessly across your enterprise through our IP TV/Digital TV.' },
    { source: '/assets/icon_panicbutton.webp', alt:'panic button', width: 50, height: 50, status: false, nav: '', productName: 'Panic Button', productDesc: 'Provide peace of mind with an instant connection to emergency services at the push of a button.' },
    { source: '/assets/icon_sdwan.webp', alt:'sd wan connectivity', width: 50, height: 50, status: true, nav: '/enterprise/connectivity', productName: 'SD Wan Connection', productDesc: 'Ensure reliable, secure, and flexible connections across your organization, reducing operational costs.' },
    { source: '/assets/icon_smartparking.webp', alt:'smart parking', width: 50, height: 50, status: false, nav: '', productName: 'Smart Parking', productDesc: 'Use real-time data to efficiently manage parking spaces, reducing congestion and improving visitor satisfaction.' },
    { source: '/assets/icon_smartcool.webp', alt:'smart cool management', width: 50, height: 50, status: false, nav: '', productName: 'Smart Cool Management', productDesc: 'Our intelligent cooling system optimizes temperature control for comfort and energy savings.' },
    { source: '/assets/icon_smartfacility.webp', alt:'smart facility management', width: 50, height: 50, status: false, nav: '', productName: 'Smart Facility Management', productDesc: 'Enhance building efficiency and comfort. Automate lighting, heating, and security for a smarter, more sustainable facility.' },
    { source: '/assets/icon_smartwaste.webp', alt:'smart waste management', width: 50, height: 50, status: false, nav: '', productName: 'Smart Waste Management', productDesc: 'Revolutionize waste collection. Utilize sensor-based insights to improve efficiency, reduce costs, and contribute to a cleaner environment.' },
    { source: '/assets/icon_smartwater.webp', alt:'smart water management', width: 50, height: 50, status: false, nav: '', productName: 'Smart Water Management', productDesc: 'Achieve sustainable water use, monitor and control water usage in real-time to conserve resources and lower expenses.' },
    { source: '/assets/icon_digitalsignage.webp', alt:'digital signage', width: 50, height: 50, status: false, nav: '', productName: 'Digital Signage', productDesc: 'Display dynamic content easily across multiple locations to communicate effectively, engage, and inform your audience.' },
    { source: '/assets/icon_absence.webp', alt:'absence system', width: 50, height: 50, status: false, nav: '', productName: 'Absence System', productDesc: 'Streamline attendance tracking: automate record-keeping, reduce paperwork, and improve the accuracy of attendance data.' }
]